FROM ejabberd/ecs:latest

# Copy ejabberd.yml config file
COPY ejabberd.yml /etc/ejabberd/ejabberd.yml

# Copy SSL certificates
COPY ejabberd.pem /etc/ejabberd/ejabberd.pem
COPY ejabberd.key /etc/ejabberd/ejabberd.key

# Set permissions for SSL certificates (Linux Only)
# RUN chmod 600 /etc/ejabberd/ejabberd.pem /etc/ejabberd/ejabberd.key

# Expose necessary ports
EXPOSE 5222 5269 5280 4369 9100

# Start Ejabberd service
CMD ["ejabberdctl", "foreground"]