apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "ejabberd_db"
            - name: POSTGRES_USER
              value: "ejabberd_user"
            - name: POSTGRES_PASSWORD
              value: "yourpassword"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
      - name: initdb
        configMap:
          name: postgres-initdb-configmap
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-configmap
data:
  init.sql: |
    CREATE USER ejabberd_user WITH PASSWORD 'yourpassword';
    CREATE DATABASE ejabberd_db;
    GRANT ALL PRIVILEGES ON DATABASE ejabberd_db TO ejabberd_user;

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
